"use client"

import { useState } from "react"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Label } from "@/components/ui/label"
import { Checkbox } from "@/components/ui/checkbox"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { useBudget } from "@/lib/budget-context"
import { FileText, Download, Loader2 } from "lucide-react"

export function ReportGenerator() {
  const { budgets, anomalies } = useBudget()
  const [selectedBudget, setSelectedBudget] = useState<string>("")
  const [includeExpenses, setIncludeExpenses] = useState(true)
  const [includeCharts, setIncludeCharts] = useState(true)
  const [includeAnomalies, setIncludeAnomalies] = useState(true)
  const [generating, setGenerating] = useState(false)
  const [reportReady, setReportReady] = useState(false)

  const exceededBudgets = budgets.filter((b) => b.status === "exceeded")

  const handleGenerateReport = async () => {
    setGenerating(true)
    // Simulate report generation
    await new Promise((resolve) => setTimeout(resolve, 2000))
    setGenerating(false)
    setReportReady(true)
  }

  const handleDownloadPDF = () => {
    // Create a simple PDF-like report content
    const selectedBudgetData = budgets.find((b) => b.id === selectedBudget) || exceededBudgets[0]
    const relatedAnomaly = anomalies.find((a) => a.budgetId === selectedBudgetData?.id)

    const reportContent = `
BUDGET ANOMALY REPORT
=====================

Report Generated: ${new Date().toLocaleDateString()}
Report Type: Budget Exceedance Analysis

EXECUTIVE SUMMARY
-----------------
Event: ${selectedBudgetData?.eventName || "All Events"}
Team: ${selectedBudgetData?.team || "All Teams"}
Status: BUDGET EXCEEDED

BUDGET DETAILS
--------------
Allocated Budget: $${selectedBudgetData?.allocatedAmount.toLocaleString() || "0"}
Amount Spent: $${selectedBudgetData?.spentAmount.toLocaleString() || "0"}
Variance: $${((selectedBudgetData?.spentAmount || 0) - (selectedBudgetData?.allocatedAmount || 0)).toLocaleString()}
Percentage Over Budget: ${relatedAnomaly?.percentageOver.toFixed(1) || "0"}%

ANOMALY INFORMATION
-------------------
Detection Date: ${relatedAnomaly?.detectedAt || "N/A"}
Current Status: ${relatedAnomaly?.status?.toUpperCase() || "PENDING"}
Reason: ${relatedAnomaly?.reason || "No reason provided"}

RECOMMENDATIONS
---------------
1. Review expense documentation for accuracy
2. Identify cost reduction opportunities
3. Update budget allocation guidelines
4. Implement spending alerts at 80% threshold

APPROVAL REQUIRED
-----------------
This budget exceedance requires review and approval from:
- Finance Head
- Department Manager
- Executive Council (if >20% over budget)

---
This report was automatically generated by BudgetTrack Dashboard
    `

    // Create and download as text file (simulating PDF)
    const blob = new Blob([reportContent], { type: "text/plain" })
    const url = URL.createObjectURL(blob)
    const a = document.createElement("a")
    a.href = url
    a.download = `budget-report-${selectedBudgetData?.eventName?.replace(/\s+/g, "-").toLowerCase() || "all"}-${new Date().toISOString().split("T")[0]}.txt`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  return (
    <Card className="bg-card">
      <CardHeader>
        <CardTitle className="flex items-center gap-2 text-foreground">
          <FileText className="h-5 w-5" />
          Generate Report
        </CardTitle>
        <CardDescription>Create a detailed PDF report for budget anomalies to present to higher-ups</CardDescription>
      </CardHeader>
      <CardContent className="space-y-6">
        <div className="space-y-2">
          <Label>Select Budget</Label>
          <Select value={selectedBudget} onValueChange={setSelectedBudget}>
            <SelectTrigger>
              <SelectValue placeholder="Select a budget with anomaly" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">All Exceeded Budgets</SelectItem>
              {exceededBudgets.map((budget) => (
                <SelectItem key={budget.id} value={budget.id}>
                  {budget.eventName} - {budget.team}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>

        <div className="space-y-4">
          <Label>Include in Report</Label>
          <div className="space-y-3">
            <div className="flex items-center space-x-2">
              <Checkbox
                id="expenses"
                checked={includeExpenses}
                onCheckedChange={(checked) => setIncludeExpenses(checked as boolean)}
              />
              <Label htmlFor="expenses" className="font-normal">
                Detailed expense breakdown
              </Label>
            </div>
            <div className="flex items-center space-x-2">
              <Checkbox
                id="charts"
                checked={includeCharts}
                onCheckedChange={(checked) => setIncludeCharts(checked as boolean)}
              />
              <Label htmlFor="charts" className="font-normal">
                Spending charts and visualizations
              </Label>
            </div>
            <div className="flex items-center space-x-2">
              <Checkbox
                id="anomalies"
                checked={includeAnomalies}
                onCheckedChange={(checked) => setIncludeAnomalies(checked as boolean)}
              />
              <Label htmlFor="anomalies" className="font-normal">
                Anomaly analysis and recommendations
              </Label>
            </div>
          </div>
        </div>

        <div className="flex gap-3">
          <Button onClick={handleGenerateReport} disabled={generating} className="flex-1">
            {generating ? (
              <>
                <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                Generating...
              </>
            ) : (
              <>
                <FileText className="mr-2 h-4 w-4" />
                Generate Report
              </>
            )}
          </Button>

          {reportReady && (
            <Button variant="outline" onClick={handleDownloadPDF}>
              <Download className="mr-2 h-4 w-4" />
              Download PDF
            </Button>
          )}
        </div>

        {reportReady && (
          <div className="rounded-lg bg-success/10 p-4">
            <p className="text-sm text-success">
              Report generated successfully! Click "Download PDF" to save the report.
            </p>
          </div>
        )}
      </CardContent>
    </Card>
  )
}
