"use client"

import { useState, useEffect } from "react"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Label } from "@/components/ui/label"
import { Checkbox } from "@/components/ui/checkbox"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { useBudget } from "@/lib/budget-context"
import { FileText, Download, Loader2 } from "lucide-react"
import { jsPDF } from "jspdf"

export function ReportGenerator() {
  const { budgets, anomalies } = useBudget()
  const [selectedBudget, setSelectedBudget] = useState<string>("")
  const [includeExpenses, setIncludeExpenses] = useState(true)
  const [includeCharts, setIncludeCharts] = useState(true)
  const [includeAnomalies, setIncludeAnomalies] = useState(true)
  const [generating, setGenerating] = useState(false)
  const [reportReady, setReportReady] = useState(false)

  const exceededBudgets = budgets.filter((b) => b.status === "exceeded")

  // Pre-select budget from query string if provided (e.g., /reports?budgetId=xyz)
  useEffect(() => {
    if (typeof window === "undefined") return
    const params = new URLSearchParams(window.location.search)
    const budgetIdParam = params.get("budgetId")
    if (budgetIdParam && !selectedBudget) {
      // Verify the budget exists before setting
      const exists = budgets.some((b) => b.id === budgetIdParam)
      if (exists) {
        setSelectedBudget(budgetIdParam)
      }
    }
  }, [budgets, selectedBudget])

  const handleGenerateReport = async () => {
    setGenerating(true)
    // Simulate report generation
    await new Promise((resolve) => setTimeout(resolve, 2000))
    setGenerating(false)
    setReportReady(true)
  }

  const handleDownloadPDF = () => {
    const doc = new jsPDF()
    const pageWidth = doc.internal.pageSize.getWidth()
    const pageHeight = doc.internal.pageSize.getHeight()

    // Get selected budget data - handle "all" case
    const budgetsToReport = selectedBudget === "all" ? exceededBudgets : [budgets.find((b) => b.id === selectedBudget)].filter(Boolean)
    
    if (budgetsToReport.length === 0) {
      // Fallback to first exceeded budget if nothing selected
      budgetsToReport.push(exceededBudgets[0])
    }

    // Helper to add footer to current page
    const addFooter = () => {
      doc.setFontSize(8)
      doc.setTextColor(100, 100, 100)
      doc.text("This report was automatically generated by Verity", pageWidth / 2, pageHeight - 10, {
        align: "center",
      })
      doc.setTextColor(0, 0, 0)
    }

    // Generate report for each budget
    budgetsToReport.forEach((selectedBudgetData, budgetIndex) => {
      if (!selectedBudgetData) return

      let yPosition = 20
      const relatedAnomaly = anomalies.find((a) => a.budgetId === selectedBudgetData?.id)
      const budgetExpenses = selectedBudgetData?.expenses || []

      // Add page separator for multiple budgets (except first)
      if (budgetIndex > 0) {
        addFooter()
        doc.addPage()
      }

      // Helper to add new page if needed
      const checkPageBreak = (requiredSpace: number) => {
        if (yPosition + requiredSpace > pageHeight - 20) {
          addFooter()
          doc.addPage()
          yPosition = 20
          return true
        }
        return false
      }

      // Header
      doc.setFontSize(22)
      doc.setFont("helvetica", "bold")
      doc.text("BUDGET ANOMALY REPORT", pageWidth / 2, yPosition, { align: "center" })
      yPosition += 10

      doc.setFontSize(10)
      doc.setFont("helvetica", "normal")
      doc.text(`Generated: ${new Date().toLocaleString()}`, pageWidth / 2, yPosition, { align: "center" })
      yPosition += 15

      // Executive Summary Section
      doc.setFontSize(14)
      doc.setFont("helvetica", "bold")
      doc.text("EXECUTIVE SUMMARY", 15, yPosition)
      yPosition += 8

      doc.setFontSize(10)
      doc.setFont("helvetica", "normal")
      doc.text(`Event: ${selectedBudgetData?.eventName || "All Events"}`, 15, yPosition)
      yPosition += 6
      doc.text(`Team: ${selectedBudgetData?.team || "All Teams"}`, 15, yPosition)
      yPosition += 6
      doc.setTextColor(220, 38, 38) // Red color for status
      doc.text(`Status: BUDGET EXCEEDED`, 15, yPosition)
      doc.setTextColor(0, 0, 0) // Reset to black
      yPosition += 12

      // Budget Details Section
      checkPageBreak(50)
      doc.setFontSize(14)
      doc.setFont("helvetica", "bold")
      doc.text("BUDGET DETAILS", 15, yPosition)
      yPosition += 8

      doc.setFontSize(10)
      doc.setFont("helvetica", "normal")
      const allocated = selectedBudgetData?.allocatedAmount || 0
      const spent = selectedBudgetData?.spentAmount || 0
      const variance = spent - allocated
      const percentOver = relatedAnomaly?.percentageOver || 0

      doc.text(`Allocated Budget: $${allocated.toLocaleString()}`, 15, yPosition)
      yPosition += 6
      doc.text(`Amount Spent: $${spent.toLocaleString()}`, 15, yPosition)
      yPosition += 6
      doc.setTextColor(220, 38, 38)
      doc.text(`Variance: $${variance.toLocaleString()} (${percentOver.toFixed(1)}% over)`, 15, yPosition)
      doc.setTextColor(0, 0, 0)
      yPosition += 12

      // Expenses Breakdown (if enabled)
      if (includeExpenses && budgetExpenses.length > 0) {
        checkPageBreak(60)
        doc.setFontSize(14)
        doc.setFont("helvetica", "bold")
        doc.text("DETAILED EXPENSE BREAKDOWN", 15, yPosition)
        yPosition += 8

        doc.setFontSize(9)
        doc.setFont("helvetica", "normal")
        
        // Table header
        doc.setFont("helvetica", "bold")
        doc.text("Description", 15, yPosition)
        doc.text("Category", 80, yPosition)
        doc.text("Amount", 130, yPosition)
        doc.text("Date", 160, yPosition)
        yPosition += 5
        
        // Horizontal line
        doc.line(15, yPosition, pageWidth - 15, yPosition)
        yPosition += 5
        
        doc.setFont("helvetica", "normal")
        budgetExpenses.slice(0, 15).forEach((expense) => {
          checkPageBreak(8)
          const desc = expense.description.length > 30 ? expense.description.substring(0, 27) + "..." : expense.description
          doc.text(desc, 15, yPosition)
          doc.text(expense.category, 80, yPosition)
          doc.text(`$${expense.amount.toLocaleString()}`, 130, yPosition)
          doc.text(new Date(expense.date).toLocaleDateString(), 160, yPosition)
          yPosition += 6
        })
        
        if (budgetExpenses.length > 15) {
          yPosition += 3
          doc.setFontSize(8)
          doc.setTextColor(100, 100, 100)
          doc.text(`... and ${budgetExpenses.length - 15} more expenses`, 15, yPosition)
          doc.setTextColor(0, 0, 0)
          doc.setFontSize(9)
        }
        yPosition += 12
      }

      // Anomaly Information (if enabled)
      if (includeAnomalies && relatedAnomaly) {
        checkPageBreak(40)
        doc.setFontSize(14)
        doc.setFont("helvetica", "bold")
        doc.text("ANOMALY INFORMATION", 15, yPosition)
        yPosition += 8

        doc.setFontSize(10)
        doc.setFont("helvetica", "normal")
        doc.text(`Detection Date: ${new Date(relatedAnomaly.detectedAt).toLocaleString()}`, 15, yPosition)
        yPosition += 6
        doc.text(`Current Status: ${relatedAnomaly.status.toUpperCase()}`, 15, yPosition)
        yPosition += 6
        doc.text(`Reason: ${relatedAnomaly.reason || "No reason provided"}`, 15, yPosition)
        yPosition += 12
      }

      // Recommendations Section (if enabled)
      if (includeAnomalies) {
        checkPageBreak(50)
        doc.setFontSize(14)
        doc.setFont("helvetica", "bold")
        doc.text("RECOMMENDATIONS", 15, yPosition)
        yPosition += 8

        doc.setFontSize(10)
        doc.setFont("helvetica", "normal")
        const recommendations = [
          "Review expense documentation for accuracy",
          "Identify cost reduction opportunities",
          "Update budget allocation guidelines",
          "Implement spending alerts at 80% threshold",
        ]

        recommendations.forEach((rec, idx) => {
          checkPageBreak(8)
          doc.text(`${idx + 1}. ${rec}`, 20, yPosition)
          yPosition += 6
        })
        yPosition += 10
      }

      // Approval Section
      checkPageBreak(40)
      doc.setFontSize(14)
      doc.setFont("helvetica", "bold")
      doc.text("APPROVAL REQUIRED", 15, yPosition)
      yPosition += 8

      doc.setFontSize(10)
      doc.setFont("helvetica", "normal")
      doc.text("This budget exceedance requires review and approval from:", 15, yPosition)
      yPosition += 7
      doc.text("- Finance Head", 20, yPosition)
      yPosition += 6
      doc.text("- Department Manager", 20, yPosition)
      yPosition += 6
      if (percentOver > 20) {
        doc.text("- Executive Council (>20% over budget)", 20, yPosition)
        yPosition += 6
      }
    })

    // Add footer to last page
    addFooter()

    // Download the PDF
    const fileName = selectedBudget === "all" 
      ? `budget-report-all-exceeded-${new Date().toISOString().split("T")[0]}.pdf`
      : `budget-report-${budgetsToReport[0]?.eventName?.replace(/\s+/g, "-").toLowerCase() || "report"}-${new Date().toISOString().split("T")[0]}.pdf`
    doc.save(fileName)
  }

  return (
    <Card className="bg-card">
      <CardHeader>
        <CardTitle className="flex items-center gap-2 text-foreground">
          <FileText className="h-5 w-5" />
          Generate Report
        </CardTitle>
        <CardDescription>Create a detailed PDF report for budget anomalies to present to higher-ups</CardDescription>
      </CardHeader>
      <CardContent className="space-y-6">
        <div className="space-y-2">
          <Label>Select Budget</Label>
          <Select value={selectedBudget} onValueChange={setSelectedBudget}>
            <SelectTrigger>
              <SelectValue placeholder="Select a budget with anomaly" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">All Exceeded Budgets</SelectItem>
              {exceededBudgets.map((budget) => (
                <SelectItem key={budget.id} value={budget.id}>
                  {budget.eventName} - {budget.team}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>

        <div className="space-y-4">
          <Label>Include in Report</Label>
          <div className="space-y-3">
            <div className="flex items-center space-x-2">
              <Checkbox
                id="expenses"
                checked={includeExpenses}
                onCheckedChange={(checked) => setIncludeExpenses(checked as boolean)}
              />
              <Label htmlFor="expenses" className="font-normal">
                Detailed expense breakdown
              </Label>
            </div>
            <div className="flex items-center space-x-2">
              <Checkbox
                id="charts"
                checked={includeCharts}
                onCheckedChange={(checked) => setIncludeCharts(checked as boolean)}
              />
              <Label htmlFor="charts" className="font-normal">
                Spending charts and visualizations
              </Label>
            </div>
            <div className="flex items-center space-x-2">
              <Checkbox
                id="anomalies"
                checked={includeAnomalies}
                onCheckedChange={(checked) => setIncludeAnomalies(checked as boolean)}
              />
              <Label htmlFor="anomalies" className="font-normal">
                Anomaly analysis and recommendations
              </Label>
            </div>
          </div>
        </div>

        <div className="flex gap-3">
          <Button onClick={handleGenerateReport} disabled={generating || !selectedBudget} className="flex-1">
            {generating ? (
              <>
                <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                Generating...
              </>
            ) : (
              <>
                <FileText className="mr-2 h-4 w-4" />
                Generate Report
              </>
            )}
          </Button>

          {reportReady && (
            <Button variant="outline" onClick={handleDownloadPDF} disabled={!selectedBudget}>
              <Download className="mr-2 h-4 w-4" />
              Download PDF
            </Button>
          )}
        </div>

        {reportReady && (
          <div className="rounded-lg bg-success/10 p-4">
            <p className="text-sm text-success">
              Report generated successfully! Click "Download PDF" to save the report.
            </p>
          </div>
        )}
      </CardContent>
    </Card>
  )
}
