import type { Budget, Expense, Anomaly, Notification, FeedbackReport } from "./types"

export const mockBudgets: Budget[] = [
  {
    id: "1",
    eventName: "Annual Company Party",
    team: "HR Department",
    allocatedAmount: 50000,
    spentAmount: 62500,
    startDate: "2025-01-01",
    endDate: "2025-01-15",
    status: "exceeded",
    category: "Events",
    description: "Annual celebration for all employees",
    createdAt: "2024-12-01",
  },
  {
    id: "2",
    eventName: "Q1 Team Building",
    team: "Engineering",
    allocatedAmount: 25000,
    spentAmount: 18750,
    startDate: "2025-02-01",
    endDate: "2025-02-28",
    status: "active",
    category: "Team Building",
    description: "Quarterly team building activities",
    createdAt: "2025-01-15",
  },
  {
    id: "3",
    eventName: "Marketing Conference",
    team: "Marketing",
    allocatedAmount: 35000,
    spentAmount: 42000,
    startDate: "2025-03-01",
    endDate: "2025-03-05",
    status: "exceeded",
    category: "Conference",
    description: "Industry marketing conference attendance",
    createdAt: "2025-02-01",
  },
  {
    id: "4",
    eventName: "Sales Kickoff",
    team: "Sales",
    allocatedAmount: 45000,
    spentAmount: 32000,
    startDate: "2025-01-10",
    endDate: "2025-01-12",
    status: "completed",
    category: "Events",
    description: "Annual sales kickoff meeting",
    createdAt: "2024-12-15",
  },
  {
    id: "5",
    eventName: "Product Launch Event",
    team: "Product",
    allocatedAmount: 80000,
    spentAmount: 95000,
    startDate: "2025-04-01",
    endDate: "2025-04-05",
    status: "exceeded",
    category: "Launch",
    description: "New product launch celebration",
    createdAt: "2025-03-01",
  },
  {
    id: "6",
    eventName: "Training Workshop",
    team: "Operations",
    allocatedAmount: 15000,
    spentAmount: 8500,
    startDate: "2025-02-15",
    endDate: "2025-02-20",
    status: "active",
    category: "Training",
    description: "Employee skill development workshop",
    createdAt: "2025-01-20",
  },
]

export const mockExpenses: Expense[] = [
  {
    id: "1",
    budgetId: "1",
    description: "Venue Rental",
    amount: 15000,
    date: "2025-01-02",
    submittedBy: "Sarah Johnson",
    category: "Venue",
  },
  {
    id: "2",
    budgetId: "1",
    description: "Catering Services",
    amount: 22000,
    date: "2025-01-05",
    submittedBy: "Sarah Johnson",
    category: "Food",
  },
  {
    id: "3",
    budgetId: "1",
    description: "Entertainment",
    amount: 12000,
    date: "2025-01-08",
    submittedBy: "Mike Chen",
    category: "Entertainment",
  },
  {
    id: "4",
    budgetId: "1",
    description: "Decorations",
    amount: 8500,
    date: "2025-01-10",
    submittedBy: "Lisa Park",
    category: "Supplies",
  },
  {
    id: "5",
    budgetId: "1",
    description: "Photography",
    amount: 5000,
    date: "2025-01-12",
    submittedBy: "Mike Chen",
    category: "Services",
  },
  {
    id: "6",
    budgetId: "2",
    description: "Activity Center Booking",
    amount: 8000,
    date: "2025-02-05",
    submittedBy: "John Smith",
    category: "Venue",
  },
  {
    id: "7",
    budgetId: "2",
    description: "Equipment Rental",
    amount: 5500,
    date: "2025-02-10",
    submittedBy: "John Smith",
    category: "Equipment",
  },
  {
    id: "8",
    budgetId: "2",
    description: "Refreshments",
    amount: 5250,
    date: "2025-02-15",
    submittedBy: "Emily Davis",
    category: "Food",
  },
  {
    id: "9",
    budgetId: "3",
    description: "Registration Fees",
    amount: 18000,
    date: "2025-03-01",
    submittedBy: "Tom Wilson",
    category: "Registration",
  },
  {
    id: "10",
    budgetId: "3",
    description: "Travel & Accommodation",
    amount: 15000,
    date: "2025-03-02",
    submittedBy: "Tom Wilson",
    category: "Travel",
  },
  {
    id: "11",
    budgetId: "3",
    description: "Marketing Materials",
    amount: 9000,
    date: "2025-03-03",
    submittedBy: "Anna Lee",
    category: "Materials",
  },
]

export const mockAnomalies: Anomaly[] = [
  {
    id: "1",
    budgetId: "1",
    eventName: "Annual Company Party",
    team: "HR Department",
    allocatedAmount: 50000,
    exceededAmount: 12500,
    percentageOver: 25,
    detectedAt: "2025-01-13",
    status: "pending",
    reason: "Additional catering costs due to increased attendance",
  },
  {
    id: "2",
    budgetId: "3",
    eventName: "Marketing Conference",
    team: "Marketing",
    allocatedAmount: 35000,
    exceededAmount: 7000,
    percentageOver: 20,
    detectedAt: "2025-03-04",
    status: "reviewed",
    reason: "Last-minute travel upgrades required",
  },
  {
    id: "3",
    budgetId: "5",
    eventName: "Product Launch Event",
    team: "Product",
    allocatedAmount: 80000,
    exceededAmount: 15000,
    percentageOver: 18.75,
    detectedAt: "2025-04-03",
    status: "pending",
    reason: "Extended venue rental for demo setup",
  },
]

export const mockNotifications: Notification[] = [
  {
    id: "1",
    type: "alert",
    title: "Budget Exceeded",
    message: "Annual Company Party has exceeded its budget by 25%",
    timestamp: "2025-01-13T10:30:00",
    read: false,
    budgetId: "1",
  },
  {
    id: "2",
    type: "warning",
    title: "Budget Warning",
    message: "Q1 Team Building is at 75% of allocated budget",
    timestamp: "2025-02-18T14:15:00",
    read: false,
    budgetId: "2",
  },
  {
    id: "3",
    type: "alert",
    title: "Budget Exceeded",
    message: "Marketing Conference has exceeded its budget by 20%",
    timestamp: "2025-03-04T09:00:00",
    read: true,
    budgetId: "3",
  },
  {
    id: "4",
    type: "info",
    title: "Report Ready",
    message: "Q4 2024 Budget Report is ready for review",
    timestamp: "2025-01-05T08:00:00",
    read: true,
  },
  {
    id: "5",
    type: "alert",
    title: "Budget Exceeded",
    message: "Product Launch Event has exceeded its budget by 18.75%",
    timestamp: "2025-04-03T16:45:00",
    read: false,
    budgetId: "5",
  },
]

export const monthlySpendingData = [
  { month: "Jan", allocated: 95000, spent: 94500 },
  { month: "Feb", allocated: 40000, spent: 27250 },
  { month: "Mar", allocated: 35000, spent: 42000 },
  { month: "Apr", allocated: 80000, spent: 95000 },
  { month: "May", allocated: 60000, spent: 45000 },
  { month: "Jun", allocated: 55000, spent: 52000 },
]

export const categorySpendingData = [
  { name: "Events", value: 157500, color: "#6366f1" },
  { name: "Team Building", value: 18750, color: "#22c55e" },
  { name: "Conference", value: 42000, color: "#eab308" },
  { name: "Training", value: 8500, color: "#ef4444" },
  { name: "Launch", value: 95000, color: "#06b6d4" },
]

export const teamBudgetData = [
  { team: "HR", allocated: 50000, spent: 62500 },
  { team: "Engineering", allocated: 25000, spent: 18750 },
  { team: "Marketing", allocated: 35000, spent: 42000 },
  { team: "Sales", allocated: 45000, spent: 32000 },
  { team: "Product", allocated: 80000, spent: 95000 },
  { team: "Operations", allocated: 15000, spent: 8500 },
]

export const mockFeedbackReports: FeedbackReport[] = [
  {
    id: "1",
    category: "unfair-promotion",
    department: "Engineering",
    severity: "high",
    subject: "Promotion criteria not transparently communicated",
    description:
      "Recent promotions in the engineering department seemed to favor individuals based on personal relationships rather than performance metrics. Several high-performing team members were overlooked despite exceeding their goals.",
    incidentDate: "2025-01-10",
    submittedAt: "2025-01-15T09:30:00",
    status: "investigating",
    isAnonymous: true,
    trackingCode: "FB-2025-001",
    assignedTo: "HR Director",
  },
  {
    id: "2",
    category: "toxic-leadership",
    department: "Sales",
    severity: "critical",
    subject: "Manager creating hostile work environment",
    description:
      "The sales team manager frequently raises their voice during meetings, publicly criticizes team members, and takes credit for others' work. This behavior has led to decreased morale and several resignations.",
    incidentDate: "2025-01-20",
    involvedParties: "Sales Department Manager",
    submittedAt: "2025-01-22T14:15:00",
    status: "under-review",
    isAnonymous: true,
    trackingCode: "FB-2025-002",
  },
  {
    id: "3",
    category: "retaliation",
    department: "Marketing",
    severity: "medium",
    subject: "Negative treatment after raising concerns",
    description:
      "After raising concerns about project deadlines in a team meeting, I have been excluded from important meetings and received a negative performance review despite previously positive feedback.",
    incidentDate: "2025-02-01",
    submittedAt: "2025-02-05T11:00:00",
    status: "new",
    isAnonymous: true,
    trackingCode: "FB-2025-003",
  },
  {
    id: "4",
    category: "discrimination",
    department: "Operations",
    severity: "high",
    subject: "Unequal treatment in work assignments",
    description:
      "Certain team members consistently receive more favorable assignments and opportunities while others are given less visible projects regardless of qualifications or experience.",
    submittedAt: "2025-02-10T16:45:00",
    status: "new",
    isAnonymous: true,
    trackingCode: "FB-2025-004",
  },
]

export const departments = [
  "HR Department",
  "Engineering",
  "Marketing",
  "Sales",
  "Product",
  "Operations",
  "Finance",
  "Legal",
  "Customer Support",
  "Executive",
]
